### ISSUE TITLE
Hi, How can i solve this problem?

### ISSUE THREAD

**Issue by ChoiJoonho-zz** [GreatLakesEnergy/Mysql-to-influxdb#1]
> python mysql2influx.py 
> Traceback (most recent call last):
>   File "mysql2influx.py", line 12, in <module>
>     from time_utils import get_epoch_from_datetime
> **ImportError: No module named time_utils**

**Comment by jlark** [comment]
Hi @ChoiJoonho try creating a file called **init**.py in the folder you're running the code

**Comment by ChoiJoonho-zz** [comment]
sorry. I don`t understand
where is init.py? 
I just mysql2influx.py execute after download

**Comment by jlark** [comment]
Hi @ChoiJoonho ,
You need to create it in the folder where `mysql2influx.py` is. If in linux just run the command `touch __init__.py` within the folder.

**Comment by ChoiJoonho-zz** [comment]
This is problem... 

![image](https://cloud.githubusercontent.com/assets/10266892/17930665/69206b8a-6a42-11e6-8627-0a916ae982e4.png)

Is this wrong way?

**Comment by jlark** [comment]
I understand. please try running `touch __init__.py` in that folder

**Comment by ChoiJoonho-zz** [comment]
I try to touch file, but same result..

![image](https://cloud.githubusercontent.com/assets/10266892/17930836/31235660-6a43-11e6-9f24-4733958d74ea.png)

**Comment by jlark** [comment]
Hi @ChoiJoonho looks like the file was empty. I've added and updated the code.
please update your repo by running `git pull origin master` thanks!

**Comment by ChoiJoonho-zz** [comment]
I checked to filled your code in time_utils.py
I try to pull but It is not download files..

![image](https://cloud.githubusercontent.com/assets/10266892/17931422/5ab1d18e-6a46-11e6-9f84-e4c4af524da2.png)

**Comment by jlark** [comment]
I would just delete the repo and clone it again.

**Comment by ChoiJoonho-zz** [comment]
I try to remove folder and clone it again but time_utils.py files name too long error 

> git clone https://github.com/GreatLakesEnergy/Mysql-to-influxdb.git
> Cloning into 'Mysql-to-influxdb'...
> remote: Counting objects: 44, done.
> remote: Total 44 (delta 0), reused 0 (delta 0), pack-reused 44
> Unpacking objects: 100% (44/44), done.
> Checking connectivity... done.
> **error: unable to create symlink time_utils.py (File name too long)
> fatal: unable to checkout working tree**
> warning: Clone succeeded, but checkout failed.
> You can inspect what was checked out with 'git status'
> and retry the checkout with 'git checkout -f HEAD'

so I make a file of copyed your time_utils.py source code 
and Problem has been solved. 

Thank you for your help

**Comment by jlark** [comment]
Wierd, I just tried this and it worked on my side.
